ATTENDANCE_AUTOMATION/ATTENDANCE_AUTOMATION/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('attendance.urls'))
]

ATTENDANCE_AUTOMATION/attendance/urls.py
from django.urls import path

from . import views

app_name = "attendance"

urlpatterns = [
    path("",views.index,name="index"),
    path("register",views.register,name="register"),
    path("attendance",views.take_attendance,name="take_attendance")
]

ATTENDANCE_AUTOMATION/attendance/models.py
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.

class user_data(models.Model):
    rno = models.IntegerField()
    fname = models.CharField(max_length=64)
    lname = models.CharField(max_length=64)
    present = models.BooleanField()
    aruco_id = models.IntegerField(primary_key=True)

ATTENDANCE_AUTOMATION/attendance/views.py
from django.shortcuts import render
import numpy as np  
import cv2   
import glob
from .models import user_data

def index(request):      
    return render(request, 'attendance/index.html',{
        "students":user_data.objects.all()
    })

def register(request="GET"):
    if request.method == "POST":
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        roll=request.POST["roll"]
        aruco=request.POST["aruco"]
        try:
            x=user_data.objects.get(aruco_id=aruco)
            return render(request, "attendance/register.html", {
                "message": "Tag already used!"
            })
        except:
            x=user_data(fname=fname, lname=lname, rno=roll, present=False,aruco_id=aruco)
            x.save()
            return render(request, 'attendance/index.html',{
                "students":user_data.objects.all()
            })
    return render(request, "attendance/register.html")

def take_attendance(request):
    Camera_matrix=np.array([[976.9729312,0.,524.0006998],[0.,974.93730941,362.12928281],[0.,0.,1.]])
    Distortion_matrix=np.array([[-2.65932795e-01,3.04981994e+00,-1.31423363e-03,-6.12106389e-04,-1.19332537e+01]])
    params =  cv2.aruco.DetectorParameters_create()
    params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    cap=cv2.VideoCapture(0)
    frame_width = int(cap.get(3))
    frame_height = int(cap.get(4))
    size = (frame_width, frame_height)

    while(True):

        #FETCHING THE IMAGE FRAME 
        ret, frame = cap.read()
        if ret is not True:
            print("Error in video capture")
            exit()

        #USING INBUILT FUNCTION TO DETECT MARKER AND GET THE CORNERS 
        corners, ids, rejectedImgPoints=cv2.aruco.detectMarkers(frame, cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_50),parameters=params,cameraMatrix=Camera_matrix,distCoeff=Distortion_matrix)

        if ids is not None:
            try:
                user_data.objects.filter(aruco_id=ids[0][0]).update(present=True) 
            except:
                pass 
            cap.release()
            break
             
            
    return render(request, 'attendance/index.html',{
        "students":user_data.objects.all()
    })

ATTENDANCE_AUTOMATION/attendance/templates/attendance/index.html
<html lang="en">
<head>
    <title>HOMEPAGE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <H2 style="text-align:center">HOMEPAGE</H2>
    <div style="margin-top: 3%; text-align:center; margin-bottom: 3%;">
        <a href="{% url 'attendance:register'%}" class="alert alert-light">Register a new student!</a>
    </div>
    <div style="margin-top: 3%; text-align:center; margin-bottom: 3%;">
        <a href="{% url 'attendance:take_attendance'%}" class="alert alert-light">Take Attendance!</a>
    </div>
    <h3>Present students</h3>
    {% for student in students %}
    {% if student.present %}
    <li>{{student.fname}} <br> {{student.lname}} <br> {{student.rno}}</li>
    {% endif %}
    {% endfor %}
    <h3>Absent students</h3>
    {% for student in students %}
    {% if not student.present %}
    <li>{{student.fname}} <br> {{student.lname}} <br> {{student.rno}}</li>
    {% endif %}
    {% endfor %}
</body>
</html>

ATTENDANCE_AUTOMATION/attendance/templates/attendance/register.html
<html lang="en">
<head>
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <style>
        body{overflow:scroll; background-image: url("https://images.unsplash.com/photo-1580582932707-520aed937b7b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2978&q=80");}
    </style>
</head>
<body>
    <H2 style="text-align:center;margin-top: 3%;">REGISTER A NEW STUDENT</H2>
    <div style="margin-top: 3%; text-align: center; margin-bottom: 3%;">
        <button class="btn btn-dark" id="back">Go back to homepage</button>
    </div>

    <div class="card" style="margin-right: 35%; margin-left: 35%;">
        <div class="card-body">
            <div class="form-group" style="margin-top: 3%; margin-bottom: 3%; ">
                <form action="{% url 'attendance:register'%}" method="POST">
                    {% csrf_token %}
                    <label for="fname">First name:</label><br>
                    <input type="text" name="fname" placeholder="First name" class="form-control"><br>
                    <label for="lname">Last name:</label><br>
                    <input type="text" name="lname" placeholder="Last name" class="form-control"><br>
                    <label for="roll">Roll Number:</label><br>
                    <input type="integer" name="roll" placeholder="Roll number" class="form-control"><br>
                    <label for="aruco">Aruco Tag ID:</label><br>
                    <input type="integer" name="aruco" placeholder="Aruco Tag ID" class="form-control"><br><br>
                    <div style="text-align:center">
                        <button type="register" class="btn btn-dark">Submit</button>
                    </div>
                </form>
            </div>
        </div>
      </div>
    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}
</body>
<script>
    document.querySelector('#back').onclick= function() 
    {
        location.href="http://127.0.0.1:8000/"
    }
</script>
</html>